### ISSUE TITLE
ajax still refreshes page

### ISSUE THREAD

**Issue by JarOfCookies** [ibericode/mailchimp-for-wordpress#470] opened 2017-08-30 00:01 UTC
My website URL: designerspace.co

### The issue
AJAX setting still refreshes the page

### How can we reproduce this issue?
1. submit email to newsletter
2. see how it still refreshes the page
3.

### Technical info
* WordPress version: 4.8.1
* MailChimp for WordPress version: 3.3.18
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment] 2017-08-30 13:50
Hi @JarOfCookies,

It seems as if the plugin's JavaScript file is not being loaded. Can you please check whether your theme has the required `<?php wp_footer(); ?>` call before its closing `</body>` element tag?

**Comment by JarOfCookies** [comment] 2017-09-01 02:57
It does - is there a specific line of code its looking for? My code is custom . All i did was install the plugin is there anything else I should have done?

**Comment by dannyvankooten** [comment] 2017-09-01 07:19
Hi @JarOfCookies,

That is weird, because I barely see any `<script>` elements loaded near your closing body tag and usually having that `<?php wp_footer(); ?>` call will load several scripts just with a default WordPress installation already. 

Our plugin should load a JavaScript file from the `/wp-content/plugins/mc4wp-premium/ajax-forms/assets/js/ajax-forms.js` but I don't see that in your page source, so it seems something is failing at outputting the correct script elements.

Could you perhaps email us at support@mc4wp.com with login credentials and tell my team that you were referred here from this GitHub issue so that I can take a look at your theme code from up close?

**Comment by johnnylopes** [comment] 2017-09-15 10:52
I have the same problem:

Even with the premium plugin, the page still refreshing.

![image](https://user-images.githubusercontent.com/2653043/30479219-279af2f2-9a0c-11e7-8c75-f27ef5f2050d.png)

**Website:** https://siren.io/

**Comment by dannyvankooten** [comment] 2017-09-19 09:38
Hi @johnnylopes,

Did we have contact over email? I just tested your site and for me the AJAX submission worked as it should. Most likely the issue is similar to my previous reply where the theme is missing a required PHP call to load the necessary scripts.

**Comment by johnnylopes** [comment] 2017-09-20 09:53
It worked. thanks, Danny.

**Comment by johnnylopes** [comment] 2017-09-20 09:53
It worked, thanks.

**Comment by dannyvankooten** [comment] 2017-09-20 09:55
Glad to hear it @johnnylopes, thanks for letting me know!

**Closed by dannyvankooten** 2017-09-20 09:55 UTC
Labels: bug, question

**Comment by biophonc** [comment] 2019-08-08 07:55
Just for the record: I had the very same issue (no ajax submission) and the cause was a caching plugin I use (WP Fastest Cache). Once I excluded the ajax-forms.min.js, the Ajax submission works just fine.
