### ISSUE TITLE
Add-on: Email Verification

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#78] opened 2015-02-16 06:19 UTC
http://quickemailverification.com/

**Comment by dannyvankooten** [comment] 2015-06-15 14:02
Notify Xavier (who came with the initial idea) once we actually do this (if ever): https://secure.helpscout.net/conversation/71808777/1689/

**Comment by arnelap** [comment] 2018-03-22 08:54
Duplicate of https://github.com/ibericode/mailchimp-for-wordpress/issues/160

**Closed by arnelap** 2018-03-22 08:54 UTC
Labels: duplicate, feature, maybe later
