### ISSUE TITLE
Validator Error. Action must be non-empty

### ISSUE THREAD

**Issue by johnpapi2** [ibericode/mailchimp-for-wordpress#734] opened 2021-09-17 23:42 UTC
My website URL: m-shoes.gr/en

### The issue
Hello,

I added in my website the subscribe form but when check my website in validator to check the compatibility with this Web Accessibility Evaluation Tool:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fm-shoes.gr%2Fen%2F

Appears an Error: Bad value for attribute action on element form: Must be non-empty.

How can find this code:
<form id="mc4wp-form-1" class="mc4wp-form mc4wp-form-6066 mc4wp-form-theme mc4wp-form-theme-dark" method="post" data-id="6066" data-name="Newsletter" action="">

In order to remove action="" ?

or is there other way to fix this?
Thanks

### How can we reproduce this issue?
1. 
2.
3.

### Technical info
* WordPress version: Latest
* Mailchimp for WordPress version: Latest
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment] 2021-09-27 13:47
Duplicate of #730

**Closed by arnelap** 2021-09-27 13:47 UTC
