### ISSUE TITLE
Form tab won't open

### ISSUE THREAD

**Issue by ericrayl1** [ibericode/mailchimp-for-wordpress#553] opened 2018-04-25 23:27 UTC
My website URL:  www.thegamedesignersmovie.com

### The issue
The form tab on Mailchimp for Wordpress won't open.  I click on it and it just reloads the page that I am already on.

### How can we reproduce this issue?
1.  Download Mailchimp for Wordpress
2.  Install Mailchimp for Wordpress
3.  Activate Mailchimp for Wordpress
3.  Click on "Form" and get pissed off because it doesn't open.

### Technical info
* WordPress version:  4.9.5 running Mesmerize Pro theme
* MailChimp for WordPress version:  4.2.1
* Relevant plugins in case of a bug:  n/a

You guys seriously need to fix this.  I cleared my cache and also reinstalled mp4wp via .zip and it still doesn't work.

**Comment by ericrayl1** [comment] 2018-04-26 00:04
Update:  I added "-forms" to the URL address bar and hit Enter and it successfully transferred me to the form tab.  Perhaps there is something wrong with your hyperlink.

Thank you,

Eric Rayl

(I accept donations)

**Comment by arnelap** [comment] 2018-04-29 13:34
I was not able to reproduce this problem, making it very hard for us to solve the issue. Since we didn't get any other reports about this issue I will close this issue for now and keep an eye on it.

**Closed by arnelap** 2018-04-29 13:34 UTC
