### ISSUE TITLE
MC4WP form API sends opt-out to MailChimp Audience database

### ISSUE THREAD

**Issue by AnnetteB21** [ibericode/mailchimp-for-wordpress#754] opened 2022-12-11 15:52 UTC
My website URL: fleurfarm.com

### The issue
When people sign up through the integrated MC4WP form (shortcode [mc4wp_form id="3499"]) their entree gets passed through the API on to Mailchimp as an opt-out. Mailchimp support tested this yesterday with their test email address and confirmed the issue.

![image](https://user-images.githubusercontent.com/120323966/206912917-920a1292-cefc-44a1-a5e2-717b4e2595a3.png)

### How can we reproduce this issue?
1. Go to https://fleurfarm.com/newsletter/
2. Sign up
3. The API first sends an opt-out status, and then immediately sends an API subscribe-status. MailChimp now flags the email address as only eligible for transactional emails.
4. I can follow up with a screenshot of my Audience history in Mailchimp for your email address.

### Technical info
* WordPress version: 6.1.1
* Mailchimp for WordPress version: 4.9.1
* Relevant plugins in case of a bug: Mailchimp for Woocommerce (by Mailchimp), MC4WP top bar, MC4WP Premium, MC4WP Mailchimp activity, MC4WP for Wordpress (by ibericode)

**Comment by dannyvankooten** [comment] 2022-12-11 15:57
Hi Anette,IIRC this is to ensure we trigger the welcome email. If you disable this setting in your form settings then we won’t send the “unsubscribe API request” first.Op 11 dec. 2022 om 16:53 heeft AnnetteB21 ***@***.***> het volgende geschreven:﻿
My website URL: fleurfarm.com
The issue
When people sign up through the integrated MC4WP form (shortcode [mc4wp_form id="3499"]) their entree gets passed through the API on to Mailchimp as an opt-out. Mailchimp support tested this yesterday with their test email address and confirmed the issue.

How can we reproduce this issue?

Go to https://fleurfarm.com/newsletter/
Sign up
The API first sends an opt-out status, and then immediately sends an API subscribe-status. MailChimp now flags the email address as only eligible for transactional emails.
I can follow up with a screenshot of my Audience history in Mailchimp for your email address.

Technical info

WordPress version: 6.1.1
Mailchimp for WordPress version: 4.9.1
Relevant plugins in case of a bug: Mailchimp for Woocommerce (by Mailchimp), MC4WP top bar, MC4WP Premium, MC4WP Mailchimp activity, MC4WP for Wordpress (by ibericode)

**Comment by AnnetteB21** [comment] 2022-12-11 16:02
Hallo Danny, thank you for the quick response - what setting exactly do you want me to disable?

Annette
________________________________

**Comment by dannyvankooten** [comment] 2022-12-11 16:04
Hi Annette,

I just checked our codebase to confirm my previous answer and I should have worded it a little differently.

We send an unsubscribe request only if you have double opt-in enabled **and the subscriber was already on the list as `pending`** (meaning they did not yet confirm their email address). We do this to ensure that Mailchimp sends out a new confirmation email. For all other cases, we should not be sending an unsubscribe request before the subscribe request. 

Are you testing with an email address that already attempted a subscribe request? Or with a completely new email address that was not on the list before?

**Comment by AnnetteB21** [comment] 2022-12-11 16:24
Thank you, I checked: I don't have double opt-in enabled, and these are new first-time subscribers.

Mailchimp support used their test email address yesterday to verify the issue, and the same thing happened to them.

Annette

________________________________

**Comment by dannyvankooten** [comment] 2022-12-11 16:28
That is really strange @AnnetteB21. Can you please go to **MC4WP > Other** and configure the debug log to "Log Everything". If you then go through a subscribe request (using a fresh email), can you please copy the debug log contents here?

**Comment by AnnetteB21** [comment] 2022-12-11 16:39
I tried two of my email addresses (unsuccesfully, they apparently already were subscribed), and then used a new email address to subscribe succesfully.

Note pad log attached.

Annette


________________________________

**Comment by AnnetteB21** [comment] 2022-12-13 05:02
Hello Danny, was the log file I sent helpful?

Annette


On Dec 11, 2022, at 11:39 AM, Annette Bolt ***@***.***> wrote:

﻿
I tried two of my email addresses (unsuccesfully, they apparently already were subscribed), and then used a new email address to subscribe succesfully.

Note pad log attached.

Annette


________________________________

**Comment by dannyvankooten** [comment] 2022-12-13 06:35
Hello Annette,

I didn’t have any time yesterday, but hope to be able to take a closer look later today or tomorrow. I’ll let you know as soon as I did!

**Comment by dannyvankooten** [comment] 2022-12-13 11:43
Hello @AnnetteB21,

I just tested this and confirmed the issue. It's been this way for years, but I may have finally found a way to be able to work around this if one is using the default marketing permissions. So I am working on a feature where you can specify the marketing permissions to enable from the form or integration settings.

Until then we recommend not enabling the GDPR fields on your Mailchimp lists. We do recommend that you enable double opt-in though.

**Comment by AnnetteB21** [comment] 2022-12-13 12:08
It’s been like this for years, where your sign-up form sends an opt-out status to Mailchimp that marks the emailadress as not eligible for marketing emails and prevents customers from resubscribing with that email address?

Annette


On Dec 13, 2022, at 6:44 AM, Danny van Kooten ***@***.***> wrote:

﻿

Hello @AnnetteB21<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnnetteB21&data=05%7C01%7C%7Cd4c7d931e523437c7d3908dadcff541c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638065286425944868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vLsbk4IfTQnF85ehK44V6YDuytY7QCgumZ5aFhJSonA%3D&reserved=0>,

I just tested this and confirmed the issue. It's been this way for years, but I may have finally found a way to be able to work around this if one is using the default marketing permissions. So I am working on a feature where you can specify the marketing permissions to enable from the form or integration settings.

Until then we recommend not enabling the GDPR fields on your Mailchimp lists. We do recommend that you enable double opt-in though.

**Comment by dannyvankooten** [comment] 2022-12-13 12:42
@AnnetteB21 We don't send the opt-out status explicitly, this is just something that Mailchimp does if you have GDPR fields enabled on your list and we don't provide a value for them. The way to fix this is by disabling GDPR fields on your list in Mailchimp, as we don't support them yet.

That said, as I am currently working on adding support for this, how would you ideally want this to work? Should the plugin enable the marketing permission named `Email` automatically for every sign-up request it handles?

**Comment by AnnetteB21** [comment] 2022-12-13 14:03
Yes, when someone signs up to receive newsletters, they agree to receive all marketing emails.


On Dec 13, 2022, at 7:42 AM, Danny van Kooten ***@***.***> wrote:

﻿

@AnnetteB21<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnnetteB21&data=05%7C01%7C%7Cdf6e07cf06e94faba14808dadd0775de%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638065321353170526%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5KlyI97G10lLSYB%2BC%2FIAwz01UCHP76A4XqKKNjEnuXg%3D&reserved=0> We don't send the opt-out status explicitly, this is just something that Mailchimp does if you have GDPR fields enabled on your list and we don't provide a value for them. The way to fix this is by disabling GDPR fields on your list in Mailchimp, as we don't support them yet.

That said, as I am currently working on adding support for this, how would you ideally want this to work? Should the plugin enable the marketing permission named Email automatically for every sign-up request it handles?

**Comment by dannyvankooten** [comment] 2022-12-20 10:51
Closing this as it's essentially a duplicate of #593 (did not realize this right away, sorry).

**Closed by dannyvankooten** 2022-12-20 10:51 UTC

**Comment by AnnetteB21** [comment] 2023-01-01 22:14
Hello Danny, Happy New Year to you.

I just checked my Mailchimp audiences and still, with GDPR switched off, the majority of the subscribes comes over as an opt-out. I've lost hundreds of mailable email addresses because they cannot be re-subscribed.

I will have to look for a different integration. Thank you for your time,

Annette

________________________________

**Comment by AnnetteB21** [comment] 2023-07-31 20:46
Hallo Danny en team,

We hebben in het voorjaar gesproken over een bug waardoor email addresses als non-subscribe overkomen in Mailchimp vanuit Woocommerce. Julie dachten dat dat door GDPR setting kwam, maar die heb ik sindsdien aangepast.

Ik heb manueel veel addresses geconverteerd. Er zijn er nog een kleine 700 emails die nog steeds als non-subscribe staan geregisteerd. Die tellen mee als accounts, maar ik kan ze niet emailen.

Bijgevoegd een recent voorbeeld:
      
      opted-in, maar toch non-subscribed.


[cid:dfceef5d-9d69-4c66-9144-d8c009b0459d]


Hoe kunnen we dit oplossen?

website:   fleurfarm.com

Bedankt,
Annette


________________________________

**Comment by arnelap** [comment] 2023-08-01 19:27
Hi Annette, it's best to contact us on support @ mc4wp.com for support. We use Git for tracking bugs and development issues and aren't always able to respond as fast to Git issues. 

@dannyvankooten  HS ticket #36526 - maybe it's not actually related to form signups, but actually the transactional users from ecommerce sync. Will track via support ticket.

**Comment by AnnetteB21** [comment] 2023-08-01 19:38
You had asked for admin access to investigate. I can give that to you while our shop is closed. But a Zoom call would be much better. Github tickets can only document so much. You have suggested various solutions from GDPR settings to forms changes to code snippets, it feels all over the place without proper troubleshooting. I would like to investigate first. I would image you would want to know too if this could be related to your plugin?

We would perhaps have solved this in a 10 minutes screen share, rather than trying to document more. I can send an invite to the email address provided.

Annette


On Aug 1, 2023, at 3:27 PM, Arne Lap ***@***.***> wrote:

﻿

Hi Annette, it's best to contact us on support @ mc4wp.com for support. We use Git for tracking bugs and development issues and aren't always able to respond as fast to Git issues.

@dannyvankooten<https://github.com/dannyvankooten> HS ticket #36526 - maybe it's not actually related to form signups, but actually the transactional users from ecommerce sync. Will track via support ticket.
